image: instrumentisto/flutter:latest
pipelines:
  default:
    - step:
        caches:
          - flutter
        script:
          - flutter pub get
          - flutter build apk --release
        artifacts:
          - build/app/outputs/apk/release/*.apk
definitions:
  caches:
    flutter: ~/.pub-cache