image: instrumentisto/flutter:latest
pipelines:
  default:
    - step:
        name: "building the app"
        caches:
          - flutter
        script:
          - flutter pub get
          - flutter build apk --release
          - mkdir -p artifacts
          - cp build/app/outputs/flutter-apk/app-release.apk artifacts/my_flutter_app.apk
        artifacts:
          - artifacts/**
definitions:
  caches:
    flutter: ~/.pub-cache